# Generated by Django 6.0.6 on 2026-06-23 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espuma_kg_por_unidad', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tela_m_por_unidad', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('rollo_unidades_por_unidad', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_estandar', to='produccion.referencia')),
            ],
            options={
                'verbose_name_plural': 'Consumos estandar',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('espuma', 'Espuma'), ('rollo', 'Rollo'), ('tela', 'Tela')], max_length=10)),
                ('cantidad_kg', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad en kilogramos', max_digits=12)),
                ('cantidad_unidades', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en unidades (rollos)', max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_mp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('origen', models.CharField(blank=True, help_text='Descripcion del origen del movimiento', max_length=200)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='produccion.estacion')),
                ('produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='produccion.produccionregistro')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='produccion.referencia')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
