# Generated by Django 6.0.6 on 2026-06-23 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaOperario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=5000, help_text='COP por hora', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('operario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tarifas de operarios',
            },
        ),
        migrations.CreateModel(
            name='CostoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('unidades_producidas', models.PositiveIntegerField(default=0)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('costo_mo', models.DecimalField(decimal_places=2, default=0, help_text='Costo mano de obra', max_digits=12)),
                ('costo_mp', models.DecimalField(decimal_places=2, default=0, help_text='Costo materia prima', max_digits=12)),
                ('merma', models.DecimalField(decimal_places=2, default=0, help_text='Costo por merma', max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='produccion.referencia')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha', 'referencia'], name='costos_cost_fecha_6aa46d_idx'), models.Index(fields=['-fecha', 'operario'], name='costos_cost_fecha_c2c5ef_idx')],
            },
        ),
    ]
