# Generated by Django 6.0.6 on 2026-06-23 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTercerizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(help_text='Autogenerado', max_length=20, unique=True)),
                ('cantidad_salida', models.PositiveIntegerField()),
                ('cantidad_esperada', models.PositiveIntegerField(help_text='Cantidad esperada de retorno en pacas')),
                ('cantidad_retorno', models.PositiveIntegerField(blank=True, help_text='Cantidad real al retornar', null=True)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_retorno', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tercerizacion', to='produccion.referencia')),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
