# Generated by Django 6.0.6 on 2026-06-23 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo_movimiento', models.CharField(choices=[('suma', 'Suma al inventario'), ('resta', 'Resta del inventario'), ('ninguno', 'Sin movimiento de inventario')], default='suma', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('oro', 'Oro'), ('plata', 'Plata')], default='oro', max_length=10)),
                ('merma_pct', models.DecimalField(decimal_places=2, default=3.0, help_text='% de merma aplicable', max_digits=5)),
                ('consumo_espuma_kg', models.DecimalField(decimal_places=4, default=0, help_text='kg de espuma por unidad', max_digits=10)),
                ('consumo_tela_m', models.DecimalField(decimal_places=4, default=0, help_text='metros de tela por unidad', max_digits=10)),
                ('costo_mp_estandar', models.DecimalField(decimal_places=2, default=0, help_text='Costo materia prima por unidad', max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sticker_impreso', models.BooleanField(default=False)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='produccion.estacion')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='produccion.referencia')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='produccion__timesta_524f9b_idx')],
            },
        ),
    ]
